node {
   environment {
    registry = "arundhwaj/docker-nodejs-test"
    registryCredential = ‘arundhwaj123’
  }
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('Building image') 
   {
      steps
      {
        script 
        {
          docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
}
