node {
    environment{
       dockerHome = tool 'docker'
       mavenHome = tool 'maven' 
       PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
    }
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
       docker.withRegistry('https://registry.hub.docker.com', 'dockerhub')
      {
       def app = docker.build("arundhwaj/docker-nodejs-test:${commit_id}", '.').push()
     }
   }
}
